spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/to-do-list
    username: user
    password: user1234
    driver-class-name: org.mariadb.jdbc.Driver

  batch:
    job:
      names: ${job.name:NONE}

  jpa:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security: debug
#  org.hibernate.type: trace
