version: "3"
services:
  database:
    container_name: local-mariadb
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
      - ~/docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=to-do-list
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user1234
      - MYSQL_ROOT_PASSWORD=root1234
      - TZ=Asia/Seoul
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always