version: "3"
services:
  database:
    container_name: local-mariadb
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql --user 1000
      - ~/docker/mariadb/var/log/maria:/var/log/maria --user 1000
      - ~/docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=to-do-list
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user1234
      - MYSQL_ROOT_PASSWORD=root1234
      - TZ=Asia/Seoul
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always

  redis:
    container_name: local-redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ~/docker/redis/data:/data --user 1000
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf

  zookeeper-local:
    image: wurstmeister/zookeeper
    container_name: zookeeper-local
    ports:
      - "2181:2181"

  kafka-local-001:
    image: wurstmeister/kafka
    hostname: kafka-local-001
    container_name: kafka-local-001
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-local-001
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
      KAFKA_LISTENERS: INTERNAL://kafka-local-001:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-001:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper-local

  kafka-local-002:
    image: wurstmeister/kafka
    hostname: kafka-local-002
    container_name: kafka-local-002
    restart: on-failure
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: kafka-local-002
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
      KAFKA_LISTENERS: INTERNAL://kafka-local-002:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-002:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper-local

  kafka-local-003:
    image: wurstmeister/kafka
    hostname: kafka-local-003
    container_name: kafka-local-003
    restart: on-failure
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_HOST_NAME: kafka-local-003
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181/peter-kafka
      KAFKA_LISTENERS: INTERNAL://kafka-local-003:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-local-003:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper-local