version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/project/todolist/zip

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      runas: ec2-user