spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/to-do-list
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security : debug
#  org.hibernate.type: trace


## test 환경
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/to-do-list-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
