spring:
  profiles:
    include: real-db-config

logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security : debug
#  org.hibernate.type: trace


## test 환경
---

spring:
  profiles: test

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mariadb://book-springboot-webservice.c6vmpkf8olpt.ap-northeast-2.rds.amazonaws.com:3306/to_do_list_test
    username: cotgyu
    password: cotgyu123123
    driver-class-name: org.mariadb.jdbc.Driver