spring:

logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security : debug
#  org.hibernate.type: trace


## test 환경
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/to-do-list-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
