spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:mariadb://localhost:3306/to-do-list
    username: user
    password: user1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  root: info

  org.springframework.security: debug
#  org.hibernate.type: trace


script:
  path: script/batch/local/
  # path: /home/ec2-user/project/todolist/zip/